Show a better error message if gdb is missing.
Before:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }'
```

User before:

"Eh? What file?"

After:

```
thread 'main' panicked at 'failed to spawn gdb: Os { code: 2, kind: NotFound, message: "No such file or directory" }'
```

User after:

"Oops, I don't have gdb installed or in my path"

(I've been that user, and I wrote the thing!)