Add a test for https://github.com/ykjit/yk/pull/1944.
Backing out that change results in:
```
thread '<unnamed>' (1010107) panicked at ykrt/src/compile/jitc_yk/trace_builder.rs:345:21:
assertion `left == right` failed: TraceId(0) 12
  left: Some(FuncIdx(0))
 right: Some(FuncIdx(2))
```

(because the previous bid isn't tracked per-frame)