Fix build WRT inline asm in naked functions.
A recent Rust change causes:

```
error[E0787]: the `asm!` macro is not allowed in naked functions
   --> ykrt/src/compile/jitc_yk/codegen/x64/deopt.rs:321:5
    |
321 | /     std::arch::asm!(
322 | |         // Reset RSP to the end of the control point frame (this doesn't include the
323 | |         // return address which will thus be overwritten in the process)
324 | |         "mov rsp, rdi",
...   |
385 | |         options(noreturn)
386 | |     )
    | |_____^ consider using the `naked_asm!` macro instead
```

This fixes that.