Update deku and fix bitvec fallout.
Fixes:

```
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: crates.io index
required by package `bitvec v0.22.1`
    ... which satisfies dependency `bitvec = "^0.22.1"` of package `deku v0.14.1`
    ... which satisfies dependency `deku = "^0.14.1"` of package `hwtracer v0.1.0 (/home/vext01/research/yk/hwtracer)`
    ... which satisfies path dependency `hwtracer` (locked to 0.1.0) of package `tests v0.1.0 (/home/vext01/research/yk/tests)`
```

Did someone get their semver wrong?