Deserialise unimplemented constants.
Before, we serialised unimplemented LLVM constants as a zero-sized Yk
constants.

This turned out to be a big mistake, as you don't find out there's a
problem until the constant is used and you then have to go on a wild
goose chase to find out what's wrong.

This change introduces an explicit "unimplemented constant", which
crashes when you ask of it: "what's your type?" or "can I have your
bytes?". The panic message then tells you what's up right away.

This changes a yklua `db.lua` crash from:

```
thread '<unnamed>' panicked at ykrt/src/compile/jitc_yk/jit_ir.rs:880:17:
assertion `left == right` failed
  left: 0
 right: 8
```

into:

```
unimplemented const: ptr null
```

To make this happen, I had to make the existing `struct Const` into an
`enum Const` containing an `Unimplemented` variant.

I had hoped to express an unimplemented constant at the operand level
(serialising an unimplemented *operand*) but this isn't easy. Because a
constant index and the constant bytes are serialised at different times,
you don't know a constant is unimplemented until after you've already
encoded it as an instruction operand. So the "unimplementedness" has to
be in `Const` somewhere -- that's what I've done here.