Pin Rust version to avoid ICE.
```
thread 'rustc' (111114) panicked at compiler/rustc_trait_selection/src/traits/select/mod.rs:294:24:
  `TraitPredicate(<&'a Self as core::iter::IntoIterator>, polarity:Positive)` has escaping bound vars, so it cannot be wrapped in a dummy binder.
```