Fix a sliently failing test.
One of the tests was kind-of-failing with:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err`
value: "Can't mix name matching with wildcards at start of line 11."',
/home/vext01/.cargo/registry/src/github.com-1ecc6299db9ec823/lang_tester-0.7.0/src/tester.rs:717:47
```

This turns out to be a bug in our tests, but also a bug in lang_tester,
because the test should fail!

https://github.com/softdevteam/lang_tester/pull/98