Provide a meaningful error when run on a non-PT processor.
Running yk on e.g. valgrind caused a "todo" error, which wasn't very
descriptive. This commit bubbles up an `Err` which tells the user "we
currently only run if you have a CPU with PT":

  thread '<unnamed>' panicked at 'CPU doesn't support the Processor Trace (PT) feature', ykcapi/src/lib.rs:24:17

It's not pretty, but it is at least informative.